# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 457)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_hour = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_hour.setFont(font)
        self.label_hour.setObjectName("label_hour")
        self.verticalLayout.addWidget(self.label_hour)
        self.spinBox_hour = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(20)
        self.spinBox_hour.setFont(font)
        self.spinBox_hour.setObjectName("spinBox_hour")
        self.verticalLayout.addWidget(self.spinBox_hour)
        self.label_minute = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_minute.setFont(font)
        self.label_minute.setObjectName("label_minute")
        self.verticalLayout.addWidget(self.label_minute)
        self.spinBox_minute = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(20)
        self.spinBox_minute.setFont(font)
        self.spinBox_minute.setObjectName("spinBox_minute")
        self.verticalLayout.addWidget(self.spinBox_minute)
        self.label_second = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_second.setFont(font)
        self.label_second.setObjectName("label_second")
        self.verticalLayout.addWidget(self.label_second)
        self.spinBox_second = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(20)
        self.spinBox_second.setFont(font)
        self.spinBox_second.setObjectName("spinBox_second")
        self.verticalLayout.addWidget(self.spinBox_second)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.radioButton_in = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_in.setObjectName("radioButton_in")
        self.verticalLayout.addWidget(self.radioButton_in)
        self.radioButton_after = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_after.setObjectName("radioButton_after")
        self.verticalLayout.addWidget(self.radioButton_after)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.radioButton_off = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_off.setObjectName("radioButton_off")
        self.verticalLayout.addWidget(self.radioButton_off)
        self.radioButton_sleep = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_sleep.setObjectName("radioButton_sleep")
        self.verticalLayout.addWidget(self.radioButton_sleep)
        self.radioButton_restart = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_restart.setObjectName("radioButton_restart")
        self.verticalLayout.addWidget(self.radioButton_restart)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.pushButton_start)
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.verticalLayout.addWidget(self.pushButton_stop)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Timer"))
        self.label_hour.setText(_translate("MainWindow", "Hour"))
        self.label_minute.setText(_translate("MainWindow", "Minute"))
        self.label_second.setText(_translate("MainWindow", "Second"))
        self.radioButton_in.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_after.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_off.setText(_translate("MainWindow", "Off"))
        self.radioButton_sleep.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_restart.setText(_translate("MainWindow", "Restart"))
        self.pushButton_start.setText(_translate("MainWindow", "START"))
        self.pushButton_stop.setText(_translate("MainWindow", "STOP"))

